window.OBAdminCenter=async function(section,{client,rpc,select,show,run,status,esc}){
 const uid=window.OBCommerce.user?.id;if(!uid)return;
 const rows=await select('ob_settings'),settings=rows[0].value;
 if(window.OBCommerce.user?.id!==uid)return;
 if(section==='settings'){
  const texts={home_text:'Texto de Inicio (vacío conserva el actual)',about_text:'Texto de Nosotros (vacío conserva el actual)',contact_text:'Texto de Contacto (vacío conserva el actual)',banner_text:'Banner de promoción',benefits:'Beneficios para clientes',email_intro:'Introducción de correos de pedido',store_name:'Nombre de la tienda',whatsapp:'WhatsApp (código país y número)',instagram:'Instagram',tiktok:'TikTok',announcement:'Aviso de tienda',shalom_instructions:'Instrucciones Shalom',email_signature:'Firma de correos',faq:'Preguntas frecuentes',terms:'Términos y condiciones',privacy:'Privacidad',returns:'Cambios y devoluciones',shipping_policy:'Política de envíos'};
  const flags={checkout_enabled:'Habilitar compras',maintenance:'Modo mantenimiento de compras',lima_enabled:'Entregas Lima habilitadas',province_enabled:'Envíos Shalom habilitados'};
  show('<h2>Configuración de OVERBLACK</h2><p>Los cambios se aplican a la tienda. No guardes contraseñas ni credenciales aquí.</p><form id="ob-settings-form">'+Object.entries(flags).map(([k,l])=>'<label class="ob-check"><input type="checkbox" name="'+k+'" '+(settings[k]?'checked':'')+'>'+l+'</label>').join('')+'<label>Tarifa Lima S/ (vacío = sin configurar)<input name="lima_fee" type="number" min="0" max="10000" step="0.01" value="'+(settings.lima_fee===null?'':settings.lima_fee/100)+'"></label><label>Adelanto provincias (%)<input name="deposit_percent" type="number" min="1" max="100" value="'+settings.deposit_percent+'" required></label><label>Aviso de stock bajo (unidades)<input name="low_stock" type="number" min="0" max="100" value="'+settings.low_stock+'" required></label>'+Object.entries(texts).map(([k,l])=>'<label>'+l+'<textarea name="'+k+'" maxlength="4000">'+esc(settings[k]||'')+'</textarea></label>').join('')+'<label>Descuento general (%; 0 desactiva, no acumulable)<input name="general_discount" type="number" min="0" max="50" value="'+(settings.general_discount||0)+'" required></label><h3>STACK y recompensas</h3>'+[['daily_games','Partidas diarias',20],['normal_points','Puntos normales',20],['perfect_points','Puntos PERFECT',50]].map(([k,l,max])=>'<label>'+l+'<input type="number" name="'+k+'" value="'+settings[k]+'" min="1" max="'+max+'" required></label>').join('')+'<label>Recompensas (puntos=porcentaje, una por línea)<textarea name="rewards" required>'+settings.rewards.map(r=>r.join('=')).join('\n')+'</textarea></label><button>Guardar configuración</button></form>',true);
  const form=document.getElementById('ob-settings-form');
  const groups={'Tienda y contacto':['store_name','whatsapp','instagram','tiktok','announcement'],'Compras y entregas':['checkout_enabled','maintenance','lima_enabled','province_enabled','lima_fee','deposit_percent','shalom_instructions'],'Productos y promociones':['low_stock','general_discount','banner_text','benefits'],'Correos de pedidos':['email_signature','email_intro'],'STACK y recompensas':['daily_games','normal_points','perfect_points','rewards'],'Contenido y políticas':['home_text','about_text','contact_text','faq','terms','privacy','returns','shipping_policy']};
  form.querySelector('h3')?.remove();const submit=form.querySelector('button');
  for(const [title,keys] of Object.entries(groups)){const group=document.createElement('fieldset'),legend=document.createElement('legend');legend.textContent=title;group.append(legend);for(const key of keys)group.append(form.elements[key].closest('label'));form.insertBefore(group,submit);}
  const readiness=document.createElement('p');readiness.setAttribute('role','status');form.before(readiness);
  const review=()=>{const missing=[];if(form.elements.lima_enabled.checked&&form.elements.lima_fee.value==='')missing.push('tarifa Lima');for(const k of ['terms','privacy','returns','shipping_policy'])if(!form.elements[k].value.trim())missing.push(texts[k]);readiness.textContent=missing.length?'Por completar antes de vender: '+missing.join(', ')+'.':'Datos de entrega y textos completados. Revisa también productos, stock y el recorrido de compra antes de habilitar ventas.';};
  form.addEventListener('input',review);review();
  const preview=document.createElement('button');preview.type='button';preview.textContent='Vista previa del texto de correo';
  const previewText=document.createElement('pre');previewText.style.whiteSpace='pre-wrap';previewText.hidden=true;form.elements.email_intro.closest('fieldset').append(preview,previewText);
  preview.onclick=()=>{previewText.textContent=[form.elements.email_intro.value,'[Número de pedido]','[Estado, total, adelanto/saldo y referencia de envío]','Consulta los detalles en https://overblack.store/account.html',form.elements.email_signature.value].join('\n\n');previewText.hidden=false;};
  form.onsubmit=e=>{e.preventDefault();run(e.submitter,async()=>{
   if(window.OBCommerce.user?.id!==uid)return;
   const f=new FormData(form),value=Object.fromEntries(f);for(const k of Object.keys(flags))value[k]=f.has(k);
   value.lima_fee=f.get('lima_fee')===''?null:Math.round(Number(f.get('lima_fee'))*100);for(const k of ['deposit_percent','low_stock','general_discount','daily_games','normal_points','perfect_points'])value[k]=Number(f.get(k));
   value.rewards=String(f.get('rewards')).trim().split(/\r?\n/).map(row=>row.split('=').map(Number));
   const patch={},expected={};for(const k of Object.keys(value))if(JSON.stringify(value[k])!==JSON.stringify(settings[k])){patch[k]=value[k];expected[k]=settings[k];}
   if(!Object.keys(patch).length){status('No hay cambios por guardar.');return;}
   await rpc('ob_settings_patch',{p_value:patch,p_expected:expected});Object.assign(settings,patch);
   if(window.OBCommerce.user?.id!==uid)return;
   try{const latest=(await select('ob_settings'))[0].value;if(window.OBCommerce.user?.id!==uid)return;window.dispatchEvent(new CustomEvent('ob:settings',{detail:latest}));await window.OBCommerce.refresh();}catch{}
   if(window.OBCommerce.user?.id===uid)status('Cambios guardados.');
  });};
 }else if(section==='recovery'){
  const products=(await select('ob_products')).filter(p=>p.deleted_at);
  if(window.OBCommerce.user?.id!==uid)return;
  show('<h2>Recuperación de productos</h2><p>Los productos de la papelera conservan foto, precio, tallas y stock. Al restaurarlos permanecerán ocultos hasta que revises sus datos.</p>'+(!products.length?'<p>La papelera está vacía.</p>':products.map(p=>'<div class="ob-row"><span>'+esc(p.name)+'<br>'+esc(new Date(p.deleted_at).toLocaleString('es-PE'))+'</span><button data-restore="'+p.id+'">Restaurar producto</button></div>').join(''))+'<p>Esta papelera permite recuperar productos retirados desde ahora; no recupera eliminaciones anteriores.</p>',true);
  document.querySelectorAll('[data-restore]').forEach(b=>b.onclick=()=>run(b,async()=>{await rpc('ob_product_manage',{p_action:'restore',p_product:Number(b.dataset.restore)});await window.OBAdminCenter(section,{client,rpc,select,show,run,status,esc});status('Producto restaurado y oculto. Revísalo en Productos / stock antes de volver a venderlo.');}));
 }else if(section==='coupons'){
  const report=await rpc('ob_admin_report');if(window.OBCommerce.user?.id!==uid)return;
  const coupons=await select('ob_coupons');if(window.OBCommerce.user?.id!==uid)return;show('<h2>Cupones</h2><form id="ob-coupon"><label>Código<input name="code" required pattern="[A-Za-z0-9_-]{3,30}" maxlength="30"></label><label>Descuento (%)<input name="percent" type="number" min="1" max="50" required></label><label>Vencimiento<input name="expires" type="datetime-local" required></label><label class="ob-check"><input name="active" type="checkbox" checked>Activo</label><button>Crear / actualizar cupón</button></form>'+coupons.map(c=>'<p><button data-coupon="'+esc(c.code)+'">'+esc(c.code)+'</button> · '+c.percent+'% · '+esc(new Date(c.expires_at).toLocaleString('es-PE'))+' · '+(c.active?'Activo':'Inactivo')+'</p>').join(''));
  const form=document.getElementById('ob-coupon');document.querySelectorAll('[data-coupon]').forEach(b=>b.onclick=()=>{const c=coupons.find(c=>c.code===b.dataset.coupon);form.elements.code.value=c.code;form.elements.percent.value=c.percent;const d=new Date(c.expires_at);form.elements.expires.value=new Date(d.getTime()-d.getTimezoneOffset()*60000).toISOString().slice(0,16);form.elements.active.checked=c.active;});
  document.querySelectorAll('[data-coupon]').forEach(b=>{
   const c=coupons.find(c=>c.code===b.dataset.coupon),usage=(report.coupon_usage||[]).find(u=>u.code===c.code)||{};
   const info=document.createElement('span');info.textContent=' · '+(new Date(c.expires_at)<=new Date()?'Vencido · ':'')+'Pedidos sin cancelar: '+(usage.active_orders||0)+' · Entregados: '+(usage.delivered_orders||0)+' · Cancelados: '+(usage.cancelled_orders||0)+' · Descuento en entregados: S/ '+((usage.delivered_discount||0)/100).toFixed(2);b.parentElement.append(info);
  });
  form.onsubmit=e=>{e.preventDefault();run(e.submitter,async()=>{const f=new FormData(form);await rpc('ob_coupon_save',{p_code:f.get('code'),p_percent:Number(f.get('percent')),p_expires:new Date(f.get('expires')).toISOString(),p_active:f.has('active')});await window.OBAdminCenter(section,{client,rpc,select,show,run,status,esc});status('Cupón guardado.');});};
 }else{
  const data=await rpc('ob_admin_report');
  if(window.OBCommerce.user?.id!==uid)return;
  if(section==='dashboard')show('<h2>Dashboard OVERBLACK</h2><p>Clientes: '+data.customers+' · Partidas STACK: '+data.games+'</p><p>Puntos ganados: '+data.earned+' · Canjeados: '+data.spent+'</p><p>Pedidos entregados, agrupados por fecha de compra: hoy S/ '+(data.today/100).toFixed(2)+' · últimos 7 días S/ '+(data.week/100).toFixed(2)+' · mes S/ '+(data.month/100).toFixed(2)+'</p><h3>Pedidos por estado</h3>'+data.statuses.map(s=>'<p>'+esc(s.status)+': '+s.count+'</p>').join('')+'<h3>Stock bajo</h3>'+(!data.low_stock.length?'<p>No hay tallas con stock bajo.</p>':'')+data.low_stock.map(s=>'<p>'+esc(s.name)+' / '+esc(s.size)+': '+s.stock+'</p>').join('')+'<h3>Más vendidos (entregados)</h3>'+data.best_sellers.map(s=>'<p>'+esc(s.name)+': '+s.quantity+'</p>').join(''),true);
  else if(section==='errors')show('<h2>Centro de errores</h2><p>Servicio de correo: '+esc(data.mail_health?.last_status||'Todavía sin actividad')+'<br>Última revisión: '+esc(data.mail_health?.last_run?new Date(data.mail_health.last_run).toLocaleString('es-PE'):'Sin registro')+'</p><p>Correos pendientes: '+data.pending_emails+'</p>'+data.errors.map(e=>'<p>Pedido #'+e.order_id+' · Intentos: '+e.attempts+' · '+esc(e.last_error||'Pendiente de procesar')+(e.last_error?'<br><button data-retry-email="'+e.id+'">Reintentar envío</button>':'')+'</p>').join('')+'<p>Revisa el servicio de correo si los pendientes no disminuyen. Los pedidos y puntos se conservan.</p>',true);
  else if(section==='audit')show('<h2>Auditoría</h2>'+data.audit.map(e=>'<p>'+esc(new Date(e.created_at).toLocaleString('es-PE'))+' · '+esc(e.action)+' · '+esc(e.actor)+'</p>').join(''),true);
  else if(section==='manual')show('<h2>Manual privado ADMIN</h2>'+data.manual.map(t=>'<p>'+esc(t)+'</p>').join(''),true);
  document.querySelectorAll('[data-retry-email]').forEach(b=>b.onclick=()=>run(b,async()=>{await rpc('ob_retry_order_email',{p_id:Number(b.dataset.retryEmail)});await window.OBAdminCenter('errors',{client,rpc,select,show,run,status,esc});status('Correo en cola. Se procesará en la próxima revisión automática.');}));
  if(section==='dashboard'){
   const extra=document.createElement('p');extra.textContent='Puntos restituidos por cancelación: '+data.returned_points+' · Canjes menos devoluciones: '+(data.spent-data.returned_points)+' · Descuentos de pedidos entregados: S/ '+(data.delivered_discounts/100).toFixed(2);
   document.querySelector('.ob-commerce-dialog h2')?.after(extra);
  }
 }
};
