window.OBOrders=async function(ctx,isAdmin,page=0,filters={}){
 const {client,rpc,show,run,esc}=ctx,uid=window.OBCommerce.user?.id;if(!uid)return;
 const money=n=>'S/ '+(n/100).toFixed(2),code=id=>'#OB-'+String(id).padStart(5,'0');
 const date=t=>new Date(t).toLocaleString('es-PE',{timeZone:'America/Lima'})+' · Perú';
 const labels={nuevo:'Pedido recibido',confirmado:'Confirmado',pendiente_adelanto:'Pendiente de adelanto',adelanto_confirmado:'Adelanto confirmado',preparando:'Preparando',enviado:'Enviado',entregado:'Entregado / pagado',cancelado:'Cancelado'};
 const actions={nuevo:['confirmado','cancelado'],confirmado:['preparando','cancelado'],pendiente_adelanto:['adelanto_confirmado','cancelado'],adelanto_confirmado:['confirmado','cancelado'],preparando:['enviado','cancelado'],enviado:['entregado','cancelado']};
 const reload=()=>window.OBOrders(ctx,isAdmin,page,filters);
 let query=client.from('ob_orders').select('*,ob_order_items(*)').order('id',{ascending:false}).range(page*25,page*25+25);
 if(!isAdmin)query=query.eq('user_id',uid);
 if(filters.state)query=query.eq('status',filters.state);
 if(filters.method)query=query.eq('payment_method',filters.method);
 if(filters.number)query=query.eq('id',filters.number);
 const {data,error}=await query;if(error)throw error;if(window.OBCommerce.user?.id!==uid)return;
 const payment=o=>o.status==='cancelado'?'Pedido cancelado. Los puntos y el stock se han restituido. Si hubo un pago, su devolución se coordina con la tienda; cancelar no transfiere dinero.':o.status==='entregado'?'Pago total confirmado: '+money(o.total):o.payment_method==='shalom_adelanto'?(o.status==='pendiente_adelanto'?'Adelanto por recibir: ':'Adelanto confirmado: ')+money(o.advance_due)+'<br>Saldo después del adelanto: '+money(o.total-o.advance_due)+'<br>Flete de Shalom por coordinar aparte.':'Pago contraentrega pendiente: '+money(o.total);
 show('<h2>'+(isAdmin?'OVERBLACK ADMIN · Pedidos':'Mis pedidos')+'</h2><form id="ob-order-filter"><label>Estado<select name="state"><option value="">Todos</option>'+Object.entries(labels).map(([k,v])=>'<option value="'+k+'">'+v+'</option>').join('')+'</select></label><label>Entrega<select name="method"><option value="">Todas</option><option value="contra_entrega">Lima · contraentrega</option><option value="shalom_adelanto">Shalom · adelanto</option></select></label><label>Número de pedido<input name="number" inputmode="numeric" pattern="[0-9]{1,15}" maxlength="15" placeholder="Ejemplo: 123"></label><button>Filtrar pedidos</button></form>'+(!data.length?'<p>No hay pedidos para esta selección.</p>':'')+data.slice(0,25).map(o=>'<article class="ob-row"><div><h3>'+code(o.id)+' · '+esc(labels[o.status]||o.status)+'</h3><p>'+esc(date(o.created_at))+'</p>'+o.ob_order_items.map(i=>'<p>'+esc(i.name)+' / '+esc(i.size)+' × '+i.quantity+' · '+money(i.unit_price*i.quantity)+'</p>').join('')+'<p>Subtotal: '+money(o.subtotal)+'<br>Descuento: '+money(o.discount)+' · Puntos usados: '+o.points_spent+'<br>Total: <strong>'+money(o.total)+'</strong></p><p>'+payment(o)+'</p><p>'+esc(o.delivery.recipient)+' · '+esc(o.delivery.phone)+'<br>'+esc([o.delivery.department,o.delivery.province].filter(Boolean).join(' · '))+'<br>'+esc(o.delivery.address||o.delivery.destination)+' · '+esc(o.delivery.district||o.delivery.agency)+(o.delivery.reference?'<br>Referencia: '+esc(o.delivery.reference):'')+(o.tracking?'<br>Envío: '+esc(o.tracking):'')+'</p>'+(isAdmin&&['preparando','enviado'].includes(o.status)?'<form data-tracking="'+o.id+'"><label>Código o referencia de envío<input name="tracking" required maxlength="100" value="'+esc(o.tracking||'')+'"></label><button>Guardar envío</button></form>':'')+'<div class="ob-order-controls">'+(isAdmin?(actions[o.status]||[]).map(s=>'<button data-order="'+o.id+'" data-state="'+s+'">'+({confirmado:'Confirmar pedido',adelanto_confirmado:'Confirmar adelanto recibido',preparando:'Preparar pedido',enviado:'Marcar enviado',entregado:'Confirmar entrega y cobro',cancelado:'Cancelar pedido'}[s])+'</button>').join(''):'')+'<button data-history="'+o.id+'">Ver historial</button></div></div></article>').join('')+'<div class="ob-order-controls"><button id="ob-orders-prev" '+(!page?'disabled':'')+'>Anterior</button><span>Página '+(page+1)+'</span><button id="ob-orders-next" '+(data.length<=25?'disabled':'')+'>Siguiente</button></div>',true);
 const form=document.getElementById('ob-order-filter');for(const key of ['state','method','number'])form.elements[key].value=filters[key]||'';
 form.onsubmit=e=>{e.preventDefault();run(e.submitter,()=>window.OBOrders(ctx,isAdmin,0,Object.fromEntries(new FormData(form))));};
 document.getElementById('ob-orders-prev').onclick=e=>run(e.target,()=>window.OBOrders(ctx,isAdmin,page-1,filters));
 document.getElementById('ob-orders-next').onclick=e=>run(e.target,()=>window.OBOrders(ctx,isAdmin,page+1,filters));
 document.querySelectorAll('[data-order]').forEach(b=>b.onclick=()=>run(b,async()=>{
  if(window.OBCommerce.user?.id!==uid)return;
  const o=data.find(o=>String(o.id)===b.dataset.order),next=b.dataset.state;
  const question=next==='adelanto_confirmado'?'¿Verificaste que recibiste '+money(o.advance_due)+' de adelanto para '+code(o.id)+'?':next==='entregado'?'¿Confirmas la entrega y el cobro completo de '+money(o.total)+' para '+code(o.id)+'?':next==='cancelado'?'¿Cancelar '+code(o.id)+' y restituir stock y puntos? Si recibiste dinero, deberás coordinar su devolución aparte.':null;
  if(question&&!confirm(question))return;
  await rpc('ob_order_status',{p_order:o.id,p_status:next});if(window.OBCommerce.user?.id===uid)await reload();
 }));
 document.querySelectorAll('[data-tracking]').forEach(f=>f.onsubmit=e=>{e.preventDefault();run(e.submitter,async()=>{if(window.OBCommerce.user?.id!==uid)return;await rpc('ob_tracking',{p_order:Number(f.dataset.tracking),p_tracking:new FormData(f).get('tracking')});if(window.OBCommerce.user?.id===uid)await reload();});});
 async function history(id,eventPage=0){
  const events=await rpc('ob_order_history',{p_order:id,p_page:eventPage});if(window.OBCommerce.user?.id!==uid)return;
  show('<h2>Historial '+code(id)+'</h2>'+(!events.length?'<p>No hay movimientos registrados.</p>':'')+events.slice(0,50).map(e=>'<div class="ob-row"><div><b>'+esc(labels[e.status]||(e.status==='tracking_actualizado'?'Información de envío actualizada':e.status))+'</b><p>'+esc(date(e.created_at))+'</p></div></div>').join('')+'<button id="ob-event-prev" '+(!eventPage?'disabled':'')+'>Anterior</button><span>Página '+(eventPage+1)+'</span><button id="ob-event-next" '+(events.length<=50?'disabled':'')+'>Siguiente</button><button id="ob-order-back">Volver a pedidos</button>');
  document.getElementById('ob-event-prev').onclick=e=>run(e.target,()=>history(id,eventPage-1));document.getElementById('ob-event-next').onclick=e=>run(e.target,()=>history(id,eventPage+1));document.getElementById('ob-order-back').onclick=e=>run(e.target,reload);
 }
 document.querySelectorAll('[data-history]').forEach(b=>b.onclick=()=>run(b,()=>history(Number(b.dataset.history))));
};
