window.OBEditProducts=async function({client,select,rpc,show,run,status,esc}){
  const [allProducts,variants]=await Promise.all([select('ob_products'),select('ob_variants')]);
  const products=allProducts.filter(p=>!p.deleted_at);
  show('<h2>Productos / stock</h2><form id="ob-product-editor"><label>Producto<select name="product">'+products.map(p=>'<option value="'+p.id+'">'+esc(p.name)+'</option>').join('')+'</select></label><label>Foto del producto<input name="photo" type="file" accept="image/jpeg,image/png,image/webp"></label><p>JPG, PNG o WebP · máximo 5 MB. La foto se mostrará en la tienda al guardar.</p><img id="ob-product-preview" alt="Vista previa del producto" hidden style="width:100%;max-height:240px;object-fit:contain"><label>Precio S/<input name="price" type="number" min="0.01" max="100000" step="0.01" required></label><label>Talla<input name="size" list="ob-sizes" required maxlength="16" placeholder="Ej.: 40, 41 o M"></label><datalist id="ob-sizes"></datalist><label class="ob-check"><input name="available" type="checkbox"> Tengo stock en esta talla</label><label>Cantidad disponible<input name="stock" type="number" min="1" max="100000" step="1" required></label><label class="ob-check"><input name="active" type="checkbox"> Disponible para venta</label><button class="ob-submit">GUARDAR PRODUCTO</button></form><h3>Tallas guardadas</h3><div id="ob-variant-list"></div>',true);
  const metadata=document.createElement('section');
  metadata.innerHTML='<h3>Crear o editar producto</h3><form id="ob-product-meta"><label>Nombre<input name="name" required maxlength="150"></label><label>Categoría<select name="category"><option value="polos">Polo</option><option value="pantalones">Pantalón</option><option value="hoodies">Hoodie</option><option value="zapatillas">Zapatilla</option></select></label><label>Colección<select name="collection"><option value="unisex">Unisex</option><option value="hombres">Hombre</option><option value="mujeres">Mujer</option></select></label><button name="action" value="edit">Guardar nombre y clasificación</button><button name="action" value="create">Crear producto nuevo</button></form><button id="ob-delete-product">Mover a papelera (sin pedidos)</button>';
  document.getElementById('ob-product-editor').before(metadata);
  const meta=document.getElementById('ob-product-meta');
  const reload=()=>window.OBEditProducts({client,select,rpc,show,run,status,esc});
  meta.onsubmit=e=>{e.preventDefault();const action=e.submitter.value;run(e.submitter,async()=>{const data=Object.fromEntries(new FormData(meta));await rpc('ob_product_manage',{p_action:action,p_product:current()?.id||null,p_data:data});await reload();status(action==='create'?'Producto creado inactivo. Selecciónalo para añadir precio, foto y tallas.':'Datos guardados.');});};
  document.getElementById('ob-delete-product').onclick=e=>run(e.target,async()=>{if(!current()||!confirm('¿Mover este producto a la papelera? Podrás recuperarlo desde ADMIN. Solo se permite si no tiene pedidos.'))return;await rpc('ob_product_manage',{p_action:'delete',p_product:current().id});await reload();});
  const form=document.getElementById('ob-product-editor'),f=form.elements,preview=document.getElementById('ob-product-preview');let objectURL;
  const visibility=document.createElement('button');visibility.type='button';visibility.className='ob-secondary';form.before(visibility);
  const current=()=>products.find(p=>p.id===Number(f.product.value));
  const availability=()=>{f.stock.disabled=!f.available.checked;};
  const pickSize=()=>{const v=variants.find(v=>v.product_id===current().id&&v.size===f.size.value.trim());f.available.checked=!!v?.stock;f.stock.value=v?.stock||1;availability();};
  const fill=()=>{const p=current();form.hidden=!p;visibility.hidden=!p;if(!p)return;meta.elements.name.value=p.name;meta.elements.category.value=p.category;meta.elements.collection.value=p.collection;visibility.textContent=p.archived?'VOLVER A MOSTRAR EN LA TIENDA':'QUITAR DE LA TIENDA';f.active.disabled=!!p.archived;for(const option of f.product.options){const row=products.find(x=>x.id===Number(option.value));option.textContent=row.name+(row.archived?' (oculto)':'');}f.price.value=p.price?p.price/100:'';f.active.checked=p.active;f.photo.value='';f.size.value='';f.available.checked=false;f.stock.value=1;availability();if(objectURL)URL.revokeObjectURL(objectURL);preview.hidden=!p.image_path;if(p.image_path)preview.src=client.storage.from('product-images').getPublicUrl(p.image_path).data.publicUrl;else preview.removeAttribute('src');const sizes=variants.filter(v=>v.product_id===p.id);document.getElementById('ob-sizes').innerHTML=sizes.map(v=>'<option value="'+esc(v.size)+'">').join('');document.getElementById('ob-variant-list').innerHTML=sizes.length?sizes.map(v=>'<button type="button" data-size="'+esc(v.size)+'">'+esc(v.size)+' · '+(v.stock?v.stock+' disponibles':'Agotado')+'</button><button type="button" data-delete-size="'+esc(v.size)+'">Eliminar talla</button>').join(' '):'<p>Aún no hay tallas. Guarda una y luego añade la siguiente.</p>';document.querySelectorAll('[data-delete-size]').forEach(b=>b.onclick=()=>run(b,async()=>{if(!confirm('¿Eliminar esta talla?'))return;await rpc('ob_product_manage',{p_action:'delete_size',p_product:current().id,p_data:{size:b.dataset.deleteSize}});await reload();}));document.querySelectorAll('[data-size]').forEach(b=>b.onclick=()=>{f.size.value=b.dataset.size;pickSize();});};
  visibility.onclick=()=>run(visibility,async()=>{const p=current(),hidden=!p.archived;await rpc('ob_product_visibility',{p_product:p.id,p_hidden:hidden});p.archived=hidden;if(hidden)p.active=false;fill();status(hidden?'Producto quitado de la tienda. Su foto, tallas e historial se conservan.':'Producto visible de nuevo. Revisa el stock y marca Disponible para venta cuando corresponda.');});
  f.product.onchange=fill;f.size.oninput=pickSize;f.available.onchange=availability;
  f.photo.onchange=()=>{const file=f.photo.files[0];if(!file)return;if(!['image/jpeg','image/png','image/webp'].includes(file.type)||file.size>5242880){f.photo.value='';status('Elige JPG, PNG o WebP de hasta 5 MB.');return;}if(objectURL)URL.revokeObjectURL(objectURL);objectURL=URL.createObjectURL(file);preview.src=objectURL;preview.hidden=false;};
  async function optimizePhoto(file){
    if(!window.createImageBitmap)return file;
    let bitmap;
    try{
      bitmap=await createImageBitmap(file);
      const scale=Math.min(1,1600/Math.max(bitmap.width,bitmap.height));
      const canvas=document.createElement('canvas');canvas.width=Math.max(1,Math.round(bitmap.width*scale));canvas.height=Math.max(1,Math.round(bitmap.height*scale));
      const context=canvas.getContext('2d');if(!context)return file;
      context.drawImage(bitmap,0,0,canvas.width,canvas.height);
      const blob=await new Promise(resolve=>canvas.toBlob(resolve,'image/webp',0.86));
      return blob?.type==='image/webp'&&blob.size<file.size?blob:file;
    }catch{return file;}finally{bitmap?.close();}
  }
  form.onsubmit=e=>{e.preventDefault();run(e.submitter,async()=>{const p=current(),file=f.photo.files[0],price=Math.round(Number(f.price.value)*100),size=f.size.value.trim(),stock=f.available.checked?Number(f.stock.value):0,active=f.active.checked;let path=p.image_path;
    if(!size||!Number.isInteger(stock)||stock<0||stock>100000)throw Error('Revisa la talla y la cantidad.');
    if(file){if(!['image/jpeg','image/png','image/webp'].includes(file.type)||file.size>5242880)throw Error('Imagen no válida.');status('Preparando y guardando la foto…');const photo=await optimizePhoto(file);path=p.id+'/'+crypto.randomUUID()+'.'+({'image/jpeg':'jpg','image/png':'png','image/webp':'webp'}[photo.type]);const {error}=await client.storage.from('product-images').upload(path,photo,{contentType:photo.type,upsert:false});if(error)throw error;}
    await rpc('ob_product_save',{p_product:p.id,p_price:price,p_active:active,p_size:size,p_stock:stock,p_image:path});
    p.price=price;p.active=active;p.image_path=path;const v=variants.find(v=>v.product_id===p.id&&v.size===size);if(v)v.stock=stock;else variants.push({product_id:p.id,size,stock});fill();f.size.value=size;pickSize();status('Foto, precio y stock guardados. Puedes añadir otra talla.');
  });};fill();
};
