-- Prices are integer céntimos. Mutations with monetary value run atomically here.
create schema if not exists private;
revoke all on schema private from public, anon, authenticated;
create table private.admins (
  slot smallint primary key check (slot in (1,2)),
  user_id uuid not null unique references auth.users(id)
);
create function public.ob_is_admin() returns boolean language sql stable security definer
set search_path = '' as $$ select exists(select 1 from private.admins where user_id=auth.uid()) $$;

create table public.ob_profiles (
  id uuid primary key references auth.users(id),
  username text not null default '' check (length(username)<=80),
  points integer not null default 0 check(points>=0),
  best integer not null default 0,
  best_score integer not null default 0,
  created_at timestamptz not null default now()
);
create function private.new_customer() returns trigger language plpgsql security definer set search_path='' as $$
begin
  insert into public.ob_profiles(id,username) values(new.id,left(coalesce(new.raw_user_meta_data->>'username',''),80));
  return new;
end $$;
create trigger ob_new_customer after insert on auth.users for each row execute function private.new_customer();
insert into public.ob_profiles(id,username) select id,left(coalesce(raw_user_meta_data->>'username',''),80) from auth.users on conflict do nothing;

create table public.ob_products (
  id bigint primary key generated by default as identity,
  name text not null check(length(name) between 1 and 150),
  category text not null check(category in ('polos','pantalones','zapatillas','hoodies')),
  collection text not null default 'unisex' check(collection in ('unisex','hombres','mujeres')),
  price integer check(price>0 and price<=10000000),
  active boolean not null default false
);
insert into public.ob_products(name,category) values
('Polo Oversize Shadow','polos'),('Polo Oversize Basic','polos'),('Cargo Urban Black','pantalones'),
('Jogger Street','pantalones'),('Sneakers Urban X','zapatillas'),('Sneakers Black Low','zapatillas'),
('Polo Oversize Graphic','polos'),('Cargo Wide Fit','pantalones');
create table public.ob_variants (
  id uuid primary key default gen_random_uuid(),
  product_id bigint not null references public.ob_products(id),
  size text not null check(length(size) between 1 and 16),
  stock integer not null default 0 check(stock between 0 and 100000),
  unique(product_id,size)
);
create table public.ob_shipping (
  id uuid primary key default gen_random_uuid(),
  department text not null, province text not null, district text not null,
  fee integer not null check(fee between 0 and 1000000),
  active boolean not null default true,
  unique(department,province,district)
);
create table public.ob_addresses (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null default auth.uid() references public.ob_profiles(id),
  recipient text not null check(length(recipient) between 3 and 150),
  phone text not null check(phone ~ '^[+]?[0-9 ()-]{9,20}$'),
  shipping_id uuid not null references public.ob_shipping(id),
  address text not null check(length(address) between 5 and 250),
  reference text not null default '' check(length(reference)<=250)
);
create table public.ob_orders (
  id bigint primary key generated always as identity,
  user_id uuid not null references public.ob_profiles(id),
  request_id uuid not null,
  status text not null default 'nuevo' check(status in ('nuevo','preparando','enviado','entregado','cancelado')),
  payment_method text not null default 'contra_entrega' check(payment_method='contra_entrega'),
  subtotal integer not null, shipping integer not null, discount integer not null,
  points_spent integer not null check(points_spent in(0,2500,5000,10000)),
  total integer not null check(total>0),
  delivery jsonb not null,
  created_at timestamptz not null default now(),
  unique(user_id,request_id)
);
create table public.ob_order_items (
  order_id bigint not null references public.ob_orders(id),
  variant_id uuid not null references public.ob_variants(id),
  name text not null, size text not null, quantity integer not null check(quantity between 1 and 20),
  unit_price integer not null,
  primary key(order_id,variant_id)
);
create table public.ob_points_ledger (
  id bigint primary key generated always as identity,
  user_id uuid not null references public.ob_profiles(id),
  delta integer not null, reason text not null, reference text,
  created_at timestamptz not null default now()
);
create table private.email_outbox (
  order_id bigint primary key references public.ob_orders(id),
  attempts integer not null default 0, locked_until timestamptz,
  sent_at timestamptz, last_error text
);
create table private.order_events (
  id bigint primary key generated always as identity,
  order_id bigint references public.ob_orders(id), actor uuid,
  status text, created_at timestamptz not null default now()
);
create table private.stack_games (
  id uuid primary key default gen_random_uuid(), user_id uuid not null references public.ob_profiles(id),
  day date not null default (now() at time zone 'America/Lima')::date,
  started_at timestamptz not null default clock_timestamp(),
  tick_at timestamptz not null default clock_timestamp(),
  elapsed double precision not null default 0,
  x double precision not null default 150, width double precision not null default 300,
  height integer not null default 0, score integer not null default 0,
  state text not null default 'moving' check(state in('moving','paused','over')),
  last_request uuid, last_response jsonb
);
create index on private.stack_games(user_id,day);
create index on public.ob_orders(user_id,created_at);
create index on public.ob_points_ledger(user_id,created_at);

-- Explicit grants AND row policies; users cannot write balances, stock, or orders.
do $$
declare t text;
begin
  foreach t in array array['ob_profiles','ob_products','ob_variants','ob_shipping','ob_addresses','ob_orders','ob_order_items','ob_points_ledger'] loop
    execute format('alter table public.%I enable row level security',t);
    execute format('revoke all on public.%I from anon,authenticated',t);
    execute format('grant select on public.%I to authenticated',t);
  end loop;
end $$;
grant select on public.ob_products,public.ob_variants,public.ob_shipping to anon;
grant insert,update,delete on public.ob_addresses to authenticated;
grant update(username) on public.ob_profiles to authenticated;
create policy profile_read on public.ob_profiles for select to authenticated using(id=auth.uid() or public.ob_is_admin());
create policy profile_edit on public.ob_profiles for update to authenticated using(id=auth.uid()) with check(id=auth.uid());
create policy products_read on public.ob_products for select to anon,authenticated using(true);
create policy variants_read on public.ob_variants for select to anon,authenticated using(true);
create policy shipping_read on public.ob_shipping for select to anon,authenticated using(active or public.ob_is_admin());
create policy address_read on public.ob_addresses for select to authenticated using(user_id=auth.uid());
create policy address_insert on public.ob_addresses for insert to authenticated with check(user_id=auth.uid());
create policy address_update on public.ob_addresses for update to authenticated using(user_id=auth.uid()) with check(user_id=auth.uid());
create policy address_delete on public.ob_addresses for delete to authenticated using(user_id=auth.uid());
create policy orders_read on public.ob_orders for select to authenticated using(user_id=auth.uid() or public.ob_is_admin());
create policy items_read on public.ob_order_items for select to authenticated using(exists(select 1 from public.ob_orders o where o.id=order_id and (o.user_id=auth.uid() or public.ob_is_admin())));
create policy ledger_read on public.ob_points_ledger for select to authenticated using(user_id=auth.uid() or public.ob_is_admin());

create function public.ob_account() returns jsonb language plpgsql security definer set search_path='' as $$
declare p public.ob_profiles; used integer;
begin
 if auth.uid() is null then raise exception 'Inicia sesión para continuar'; end if;
 select * into strict p from public.ob_profiles where id=auth.uid();
 select count(*) into used from private.stack_games where user_id=p.id and day=(now() at time zone 'America/Lima')::date;
 return to_jsonb(p)||jsonb_build_object('used',used,'admin',public.ob_is_admin());
end $$;

-- Start consumes one of five attempts under the same per-user lock.
-- A drop uses SERVER time and geometry; client-supplied coordinates/scores are never accepted.
create function public.ob_stack(p_action text, p_game uuid default null, p_step integer default 0, p_request uuid default null)
returns jsonb language plpgsql security definer set search_path='' as $$
declare g private.stack_games; t timestamptz:=clock_timestamp(); age double precision;
 travel double precision; lim double precision; pos double precision; w double precision; l double precision;
 perfect boolean; pts integer:=0; answer jsonb; uid uuid:=auth.uid();
begin
 if uid is null then raise exception 'Inicia sesión para jugar'; end if;
 perform 1 from public.ob_profiles where id=uid for update;
 if p_request is null then raise exception 'Falta identificador de operación'; end if;
 if p_action='start' then
   select * into g from private.stack_games where user_id=uid and last_request=p_request;
   if found then return g.last_response; end if;
   if (select count(*) from private.stack_games where user_id=uid and day=(t at time zone 'America/Lima')::date)>=5 then raise exception 'Ya jugaste tus 5 partidas de hoy. Vuelve mañana.'; end if;
   update private.stack_games set state='over' where user_id=uid and state<>'over';
   insert into private.stack_games(user_id,day,started_at,tick_at) values(uid,(t at time zone 'America/Lima')::date,t,t) returning * into g;
 else
   select * into g from private.stack_games where id=p_game and user_id=uid for update;
   if not found then raise exception 'Partida no encontrada'; end if;
   if g.last_request=p_request then return g.last_response; end if;
   if g.state='over' or t-g.started_at>interval '30 minutes' then raise exception 'La partida terminó o caducó'; end if;
   if p_step<>g.height then raise exception 'La partida cambió; vuelve a intentarlo'; end if;
   age:=g.elapsed + case when g.state='moving' then extract(epoch from t-g.tick_at) else 0 end;
   if p_action='pause' then g.elapsed:=age; g.state:='paused';
   elsif p_action='resume' then
     if g.state<>'paused' then raise exception 'La partida no está en pausa'; end if;
     g.state:='moving'; g.tick_at:=t;
   elsif p_action='drop' then
     if g.state<>'moving' or age<0.12 then raise exception 'Espera antes de soltar'; end if;
     lim:=600-g.width-14;
     travel:=mod((145*(1+g.height*0.055)*age)::numeric,(2*lim)::numeric)::double precision;
     pos:=case when travel<=lim then travel else 2*lim-travel end;
     if mod(g.height,2)=1 then pos:=lim-pos; end if;
     perfect:=abs(pos-g.x)<=least(6,g.width*0.12);
     l:=greatest(g.x,pos); w:=least(g.x+g.width,pos+g.width)-l;
     if perfect then l:=g.x; w:=g.width; pts:=5;
     elsif w>0 then pts:=2; end if;
     if pts=0 then g.state:='over';
     else
       g.x:=l; g.width:=w; g.height:=g.height+1; g.score:=g.score+pts;
       -- Fall animation runs for 160ms before the next box starts moving.
       g.tick_at:=t+interval '160 milliseconds'; g.elapsed:=0;
       if g.height>=300 then g.state:='over'; end if;
       update public.ob_profiles set points=points+pts,best=greatest(best,g.height),best_score=greatest(best_score,g.score) where id=uid;
       insert into public.ob_points_ledger(user_id,delta,reason,reference) values(uid,pts,'stack',g.id::text||':'||g.height);
     end if;
   else raise exception 'Acción desconocida'; end if;
 end if;
 answer:=jsonb_build_object('id',g.id,'x',g.x,'width',g.width,'height',g.height,'score',g.score,'state',g.state,'points',pts,'perfect',coalesce(perfect,false),'drop_x',pos,'elapsed',greatest(0,g.elapsed+case when g.state='moving' then extract(epoch from t-g.tick_at) else 0 end),'delay',greatest(0,extract(epoch from g.tick_at-t)),'account',public.ob_account());
 update private.stack_games set x=g.x,width=g.width,height=g.height,score=g.score,state=g.state,tick_at=g.tick_at,elapsed=g.elapsed,last_request=p_request,last_response=answer where id=g.id;
 return answer;
end $$;

-- Quote/checkout share validation. Commit locks user, price rows, stock in sorted order.
create function public.ob_checkout(p_items jsonb,p_delivery jsonb,p_reward integer default 0,p_request uuid default null,p_commit boolean default false)
returns jsonb language plpgsql security definer set search_path='' as $$
declare uid uuid:=auth.uid(); balance integer; ship public.ob_shipping; item record;
 subtotal integer:=0; discount integer; percent integer; result jsonb; existing public.ob_orders;
 v_order_id bigint; lines jsonb:='[]'; delivery jsonb; n integer;
begin
 if uid is null then raise exception 'Inicia sesión para comprar'; end if;
 select points into strict balance from public.ob_profiles where id=uid for update;
 if p_commit then
   if p_request is null then raise exception 'Falta identificador del pedido'; end if;
   select * into existing from public.ob_orders where user_id=uid and request_id=p_request;
   if found then return to_jsonb(existing)||jsonb_build_object('code','#OB-'||lpad(existing.id::text,greatest(5,length(existing.id::text)),'0')); end if;
 end if;
 if p_reward is null or p_reward not in(0,2500,5000,10000) then raise exception 'Recompensa no válida'; end if;
 if balance<p_reward then raise exception 'No tienes suficientes puntos'; end if;
 percent:=case p_reward when 2500 then 5 when 5000 then 10 when 10000 then 15 else 0 end;
 if jsonb_typeof(p_items) is distinct from 'array' then raise exception 'Carrito no válido'; end if;
 if jsonb_array_length(p_items) not between 1 and 30 then raise exception 'Carrito vacío o demasiado grande'; end if;
 if exists(select 1 from jsonb_array_elements(p_items) e where jsonb_typeof(e->'quantity') is distinct from 'number' or (e->>'quantity') !~ '^[0-9]+$' or (e->>'quantity')::numeric not between 1 and 20 or e->>'variant_id' is null) then raise exception 'Cantidad no válida'; end if;
 if (select count(distinct e->>'variant_id') from jsonb_array_elements(p_items) e)<>jsonb_array_length(p_items) then raise exception 'Variantes duplicadas'; end if;
 select * into ship from public.ob_shipping where id=(p_delivery->>'shipping_id')::uuid and active for share;
 if not found then raise exception 'Selecciona una zona de envío disponible'; end if;
 if length(trim(coalesce(p_delivery->>'recipient',''))) not between 3 and 150 or
    coalesce(p_delivery->>'phone','') !~ '^[+]?[0-9 ()-]{9,20}$' or
    length(trim(coalesce(p_delivery->>'address',''))) not between 5 and 250 or
    length(coalesce(p_delivery->>'reference',''))>250 then raise exception 'Completa los datos de entrega'; end if;
 delivery:=jsonb_build_object('recipient',trim(p_delivery->>'recipient'),'phone',p_delivery->>'phone','address',trim(p_delivery->>'address'),'reference',coalesce(p_delivery->>'reference',''),'shipping_id',ship.id,'department',ship.department,'province',ship.province,'district',ship.district);
 -- Lock every requested product first, then every variant, deterministically.
 perform 1 from public.ob_products p where p.id in(select v.product_id from public.ob_variants v join jsonb_array_elements(p_items) e on v.id=(e->>'variant_id')::uuid) order by p.id for share;
 n:=0;
 for item in select v.id,v.size,v.stock,p.name,p.price,p.active,(e->>'quantity')::integer as quantity
   from jsonb_array_elements(p_items) e join public.ob_variants v on v.id=(e->>'variant_id')::uuid
   join public.ob_products p on p.id=v.product_id order by v.id for update of v loop
   n:=n+1;
   if not item.active or item.price is null then raise exception 'Producto no disponible'; end if;
   if item.stock<item.quantity then raise exception 'Stock insuficiente para % / %',item.name,item.size; end if;
   subtotal:=subtotal+item.price*item.quantity;
   lines:=lines||jsonb_build_array(jsonb_build_object('variant_id',item.id,'name',item.name,'size',item.size,'quantity',item.quantity,'unit_price',item.price));
 end loop;
 if n<>jsonb_array_length(p_items) then raise exception 'Hay productos no válidos'; end if;
 discount:=floor(subtotal::numeric*percent/100);
 result:=jsonb_build_object('subtotal',subtotal,'shipping',ship.fee,'discount',discount,'total',subtotal+ship.fee-discount,'points_spent',p_reward,'points_after',balance-p_reward,'items',lines,'delivery',delivery);
 if not p_commit then return result; end if;
 -- Require the exact reviewed total; price/fee changes require a new review.
 if (p_delivery->>'expected_total') is null or (p_delivery->>'expected_total')::integer<>subtotal+ship.fee-discount then raise exception 'El total cambió. Revisa nuevamente tu pedido.'; end if;
 insert into public.ob_orders(user_id,request_id,subtotal,shipping,discount,total,points_spent,delivery)
 values(uid,p_request,subtotal,ship.fee,discount,subtotal+ship.fee-discount,p_reward,delivery) returning id into v_order_id;
 insert into public.ob_order_items select v_order_id,(e->>'variant_id')::uuid,e->>'name',e->>'size',(e->>'quantity')::integer,(e->>'unit_price')::integer from jsonb_array_elements(lines) e;
 update public.ob_variants v set stock=v.stock-i.quantity from public.ob_order_items i where i.order_id=v_order_id and v.id=i.variant_id;
 update public.ob_profiles set points=points-p_reward where id=uid;
 if p_reward>0 then insert into public.ob_points_ledger(user_id,delta,reason,reference) values(uid,-p_reward,'reserva_pedido',v_order_id::text); end if;
 insert into private.email_outbox(order_id) values(v_order_id);
 insert into private.order_events(order_id,actor,status) values(v_order_id,uid,'nuevo');
 return result||jsonb_build_object('id',v_order_id,'code','#OB-'||lpad(v_order_id::text,greatest(5,length(v_order_id::text)),'0'),'status','nuevo');
end $$;

create function public.ob_order_status(p_order bigint,p_status text) returns void language plpgsql security definer set search_path='' as $$
declare o public.ob_orders;
begin
 if not public.ob_is_admin() then raise exception 'Acceso denegado'; end if;
 select * into strict o from public.ob_orders where id=p_order for update;
 if o.status=p_status then return; end if;
 if not ((o.status='nuevo' and p_status in('preparando','cancelado')) or (o.status='preparando' and p_status in('enviado','cancelado')) or (o.status='enviado' and p_status in('entregado','cancelado'))) then raise exception 'Cambio de estado no permitido'; end if;
 if p_status='cancelado' then
   -- Same lock order as checkout (profile then sorted variants).
   perform 1 from public.ob_profiles where id=o.user_id for update;
   perform 1 from public.ob_variants v join public.ob_order_items i on i.variant_id=v.id where i.order_id=o.id order by v.id for update of v;
   update public.ob_variants v set stock=v.stock+i.quantity from public.ob_order_items i where i.order_id=o.id and i.variant_id=v.id;
   update public.ob_profiles set points=points+o.points_spent where id=o.user_id;
   if o.points_spent>0 then insert into public.ob_points_ledger(user_id,delta,reason,reference) values(o.user_id,o.points_spent,'devolucion_pedido',o.id::text); end if;
 end if;
 update public.ob_orders set status=p_status where id=o.id;
 insert into private.order_events(order_id,actor,status) values(o.id,auth.uid(),p_status);
end $$;

create function public.ob_inventory(p_product bigint,p_price integer,p_active boolean,p_size text,p_stock integer) returns void
language plpgsql security definer set search_path='' as $$
begin
 if not public.ob_is_admin() then raise exception 'Acceso denegado'; end if;
 if p_active and p_price is null then raise exception 'Define el precio antes de activar'; end if;
 update public.ob_products set price=p_price,active=p_active where id=p_product;
 if not found then raise exception 'Producto inexistente'; end if;
 insert into public.ob_variants(product_id,size,stock) values(p_product,trim(p_size),p_stock) on conflict(product_id,size) do update set stock=excluded.stock;
end $$;
create function public.ob_shipping_save(p_department text,p_province text,p_district text,p_fee integer,p_active boolean) returns void
language plpgsql security definer set search_path='' as $$
begin
 if not public.ob_is_admin() then raise exception 'Acceso denegado'; end if;
 if length(trim(p_department)) not between 1 and 80 or length(trim(p_province)) not between 1 and 80 or length(trim(p_district)) not between 1 and 80 then raise exception 'Completa la zona'; end if;
 insert into public.ob_shipping(department,province,district,fee,active) values(trim(p_department),trim(p_province),trim(p_district),p_fee,p_active)
 on conflict(department,province,district) do update set fee=excluded.fee,active=excluded.active;
end $$;

-- Only the server-side scheduled worker can lease/email/ack notifications.
create function public.ob_email_claim() returns jsonb language plpgsql security definer set search_path='' as $$
declare q private.email_outbox; o public.ob_orders; recipients jsonb;
begin
 select * into q from private.email_outbox where sent_at is null and (locked_until is null or locked_until<now()) order by order_id for update skip locked limit 1;
 if not found then return null; end if;
 select jsonb_agg(u.email order by a.slot) into recipients from private.admins a join auth.users u on u.id=a.user_id;
 if coalesce(jsonb_array_length(recipients),0)<>2 then raise exception 'Configura los dos administradores'; end if;
 update private.email_outbox set attempts=attempts+1,locked_until=now()+interval '5 minutes' where order_id=q.order_id;
 select * into strict o from public.ob_orders where id=q.order_id;
 return jsonb_build_object('id',o.id,'total',o.total,'district',o.delivery->>'district','recipients',recipients);
end $$;
create function public.ob_email_ack(p_order bigint,p_error text default null) returns void language plpgsql security definer set search_path='' as $$
begin
 update private.email_outbox set sent_at=case when p_error is null then now() else null end,last_error=left(p_error,300),locked_until=case when p_error is null then null else now()+interval '15 minutes' end where order_id=p_order;
end $$;

-- Remove default PUBLIC execution, including helper/trigger functions.
revoke all on all functions in schema private from public,anon,authenticated;
revoke all on function public.ob_is_admin(),public.ob_account(),public.ob_stack(text,uuid,integer,uuid),public.ob_checkout(jsonb,jsonb,integer,uuid,boolean),public.ob_order_status(bigint,text),public.ob_inventory(bigint,integer,boolean,text,integer),public.ob_shipping_save(text,text,text,integer,boolean),public.ob_email_claim(),public.ob_email_ack(bigint,text) from public,anon,authenticated;
grant execute on function public.ob_is_admin() to anon,authenticated;
grant execute on function public.ob_account(),public.ob_stack(text,uuid,integer,uuid),public.ob_checkout(jsonb,jsonb,integer,uuid,boolean),public.ob_order_status(bigint,text),public.ob_inventory(bigint,integer,boolean,text,integer),public.ob_shipping_save(text,text,text,integer,boolean) to authenticated;
grant execute on function public.ob_email_claim(),public.ob_email_ack(bigint,text) to service_role;

-- Privileged implementations live outside the exposed API schema.
-- Public wrappers execute as caller; the private implementations enforce auth/roles.
alter function public.ob_is_admin() set schema private;
alter function public.ob_account() set schema private;
alter function public.ob_stack(text,uuid,integer,uuid) set schema private;
alter function public.ob_checkout(jsonb,jsonb,integer,uuid,boolean) set schema private;
alter function public.ob_order_status(bigint,text) set schema private;
alter function public.ob_inventory(bigint,integer,boolean,text,integer) set schema private;
alter function public.ob_shipping_save(text,text,text,integer,boolean) set schema private;
alter function public.ob_email_claim() set schema private;
alter function public.ob_email_ack(bigint,text) set schema private;
grant usage on schema private to anon,authenticated,service_role;
create function public.ob_is_admin() returns boolean language sql stable security invoker set search_path='' as $$select private.ob_is_admin()$$;
create function public.ob_account() returns jsonb language sql security invoker set search_path='' as $$select private.ob_account()$$;
create function public.ob_stack(p_action text,p_game uuid default null,p_step integer default 0,p_request uuid default null) returns jsonb language sql security invoker set search_path='' as $$select private.ob_stack(p_action,p_game,p_step,p_request)$$;
create function public.ob_checkout(p_items jsonb,p_delivery jsonb,p_reward integer default 0,p_request uuid default null,p_commit boolean default false) returns jsonb language sql security invoker set search_path='' as $$select private.ob_checkout(p_items,p_delivery,p_reward,p_request,p_commit)$$;
create function public.ob_order_status(p_order bigint,p_status text) returns void language sql security invoker set search_path='' as $$select private.ob_order_status(p_order,p_status)$$;
create function public.ob_inventory(p_product bigint,p_price integer,p_active boolean,p_size text,p_stock integer) returns void language sql security invoker set search_path='' as $$select private.ob_inventory(p_product,p_price,p_active,p_size,p_stock)$$;
create function public.ob_shipping_save(p_department text,p_province text,p_district text,p_fee integer,p_active boolean) returns void language sql security invoker set search_path='' as $$select private.ob_shipping_save(p_department,p_province,p_district,p_fee,p_active)$$;
create function public.ob_email_claim() returns jsonb language sql security invoker set search_path='' as $$select private.ob_email_claim()$$;
create function public.ob_email_ack(p_order bigint,p_error text default null) returns void language sql security invoker set search_path='' as $$select private.ob_email_ack(p_order,p_error)$$;
revoke all on function public.ob_is_admin(),public.ob_account(),public.ob_stack(text,uuid,integer,uuid),public.ob_checkout(jsonb,jsonb,integer,uuid,boolean),public.ob_order_status(bigint,text),public.ob_inventory(bigint,integer,boolean,text,integer),public.ob_shipping_save(text,text,text,integer,boolean),public.ob_email_claim(),public.ob_email_ack(bigint,text) from public,anon,authenticated;
grant execute on function public.ob_is_admin() to anon,authenticated;
grant execute on function public.ob_account(),public.ob_stack(text,uuid,integer,uuid),public.ob_checkout(jsonb,jsonb,integer,uuid,boolean),public.ob_order_status(bigint,text),public.ob_inventory(bigint,integer,boolean,text,integer),public.ob_shipping_save(text,text,text,integer,boolean) to authenticated;
grant execute on function public.ob_email_claim(),public.ob_email_ack(bigint,text) to service_role;
alter table private.admins enable row level security;
alter table private.stack_games enable row level security;
alter table private.email_outbox enable row level security;
alter table private.order_events enable row level security;
create index on public.ob_addresses(user_id);
create index on public.ob_order_items(variant_id);
